/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetbd1;

import javax.swing.JOptionPane;


public class EtudiantP1 extends javax.swing.JFrame {

    /**
     * Creates new form EtudiantP1
     */
    private final int numEtu;
    public EtudiantP1(int numEtu) {
        initComponents();
        this.numEtu= numEtu;
        String dateDuJour = "2018-04-08"; //est normalement la date du jour actuel mais pour la correction on a mis une date arbitraire qui correspondra à des données
        String requete = "select dateControle as Date ,nomMatiere as Matiere ,idSalle as Salle,heureDebutCont as Debut,heureFinCont as Fin from Controle natural join Passer where idGroupe= (select idGroupe from Eleve where numEtu ="+numEtu+") and dateControle > '"+dateDuJour+"' order by DateControle";
        BaseDonneeUG.metDansJTablePlanningEleve(accueilCoursTab,numEtu,10,5,dateDuJour);
        BaseDonneeUG.metDansJTable(requete,accueilExamTab,3,5 );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel37 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        accueil = new javax.swing.JLabel();
        profil = new javax.swing.JLabel();
        notes = new javax.swing.JLabel();
        planning = new javax.swing.JLabel();
        contact = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel6_Accueil = new javax.swing.JPanel();
        mainPane = new javax.swing.JTabbedPane();
        accueilPane = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        accueilCoursTab = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        accueilExamTab = new javax.swing.JTable();
        jLabel44 = new javax.swing.JLabel();
        profilPane = new javax.swing.JPanel();
        JPanel10 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        profilNom = new javax.swing.JLabel();
        profilPrenom = new javax.swing.JLabel();
        profilSexe = new javax.swing.JLabel();
        profilMail = new javax.swing.JLabel();
        profilMdp = new javax.swing.JLabel();
        profilClasse = new javax.swing.JLabel();
        profilGrp = new javax.swing.JLabel();
        profilButChangeMdp = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        profilDateN = new javax.swing.JLabel();
        notesPane = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        notesTab = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        notesCBMatiere = new javax.swing.JComboBox<>();
        notesButMoyenneMatiere = new javax.swing.JLabel();
        notesMatiere = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        notesGeneral = new javax.swing.JLabel();
        planningPane = new javax.swing.JPanel();
        planningPANE = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        planningTab = new javax.swing.JTable();
        jLabel39 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        planningExamTab = new javax.swing.JTable();
        jPanel17 = new javax.swing.JPanel();
        planningCBMatiere = new javax.swing.JComboBox<>();
        planningButRechercher = new javax.swing.JLabel();
        contactPane = new javax.swing.JPanel();
        contactPanel = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        contactTabEleve = new javax.swing.JTable();
        jLabel42 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        jScrollPane9 = new javax.swing.JScrollPane();
        contactTabProf = new javax.swing.JTable();
        contactJTF = new javax.swing.JTextField();
        recherche = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();

        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetbd1/images/titre1.png"))); // NOI18N

        jPanel15.setBackground(new java.awt.Color(249, 207, 21));
        jPanel15.setPreferredSize(new java.awt.Dimension(600, 2));

        jPanel16.setBackground(new java.awt.Color(249, 207, 21));
        jPanel16.setForeground(new java.awt.Color(249, 207, 21));
        jPanel16.setPreferredSize(new java.awt.Dimension(2, 2));

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel15Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel15Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE)))
        );

        jTable5.setBackground(new java.awt.Color(39, 26, 54));
        jTable5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(249, 207, 21)));
        jTable5.setForeground(new java.awt.Color(249, 207, 21));
        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Date", "8h - 10h", "10h - 12h", "14h - 16h", "16h - 18h"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable5.setGridColor(new java.awt.Color(249, 207, 21));
        jScrollPane5.setViewportView(jTable5);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetbd1/images/logoM.png"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(249, 207, 21)));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
        });

        accueil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetbd1/images/Clicked/accueilClicked.png"))); // NOI18N
        accueil.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(249, 207, 21), 1, true));
        accueil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                accueilMouseClicked(evt);
            }
        });

        profil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetbd1/images/profil.png"))); // NOI18N
        profil.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(249, 207, 21)));
        profil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profilMouseClicked(evt);
            }
        });

        notes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetbd1/images/notes.png"))); // NOI18N
        notes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(249, 207, 21)));
        notes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                notesMouseClicked(evt);
            }
        });

        planning.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetbd1/images/planning.png"))); // NOI18N
        planning.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(249, 207, 21)));
        planning.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                planningMouseClicked(evt);
            }
        });

        contact.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetbd1/images/contact.png"))); // NOI18N
        contact.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(249, 207, 21)));
        contact.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                contactMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(accueil)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(contact, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(planning, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(profil, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(notes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addComponent(accueil, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(profil, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(notes, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(planning, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(contact)
                .addGap(0, 0, 0))
        );

        jPanel3.setBackground(new java.awt.Color(39, 26, 54));

        jPanel6_Accueil.setBackground(new java.awt.Color(39, 26, 54));

        mainPane.setBackground(new java.awt.Color(39, 26, 54));
        mainPane.setForeground(new java.awt.Color(248, 207, 21));
        mainPane.setToolTipText("");
        mainPane.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        mainPane.setOpaque(true);
        mainPane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mainPaneMouseClicked(evt);
            }
        });

        accueilPane.setBackground(new java.awt.Color(39, 26, 54));

        jPanel10.setBackground(new java.awt.Color(39, 26, 54));

        jPanel6.setBackground(new java.awt.Color(249, 207, 21));
        jPanel6.setPreferredSize(new java.awt.Dimension(600, 2));

        jPanel11.setBackground(new java.awt.Color(249, 207, 21));
        jPanel11.setForeground(new java.awt.Color(249, 207, 21));
        jPanel11.setPreferredSize(new java.awt.Dimension(2, 2));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(920, Short.MAX_VALUE)))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE)))
        );

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetbd1/images/welcome.png"))); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetbd1/images/titre1.png"))); // NOI18N

        jPanel13.setBackground(new java.awt.Color(249, 207, 21));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        accueilCoursTab.setBackground(new java.awt.Color(39, 26, 54));
        accueilCoursTab.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(249, 207, 21)));
        accueilCoursTab.setForeground(new java.awt.Color(249, 207, 21));
        accueilCoursTab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Date", "8h - 10h", "10h - 12h", "14h - 16h", "16h - 18h"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        accueilCoursTab.setGridColor(new java.awt.Color(249, 207, 21));
        jScrollPane1.setViewportView(accueilCoursTab);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetbd1/images/titre2.png"))); // NOI18N

        accueilExamTab.setBackground(new java.awt.Color(39, 26, 54));
        accueilExamTab.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(249, 207, 21)));
        accueilExamTab.setForeground(new java.awt.Color(249, 207, 21));
        accueilExamTab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Date", "Matière", "Salle", "Heure de début", "Heure de fin"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        accueilExamTab.setGridColor(new java.awt.Color(249, 207, 21));
        jScrollPane2.setViewportView(accueilExamTab);

        jLabel44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetbd1/images/logout2.png"))); // NOI18N
        jLabel44.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel44MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(231, 231, 231)
                .addComponent(jLabel44))
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel13))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 834, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 835, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 48, Short.MAX_VALUE))
            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 932, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );

        javax.swing.GroupLayout accueilPaneLayout = new javax.swing.GroupLayout(accueilPane);
        accueilPane.setLayout(accueilPaneLayout);
        accueilPaneLayout.setHorizontalGroup(
            accueilPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        accueilPaneLayout.setVerticalGroup(
            accueilPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        mainPane.addTab("Accueil", accueilPane);

        JPanel10.setBackground(new java.awt.Color(39, 26, 54));

        jPanel7.setBackground(new java.awt.Color(249, 207, 21));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetbd1/images/infoPerso400x46.png"))); // NOI18N

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(249, 207, 21));
        jLabel17.setText("Nom :");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(249, 207, 21));
        jLabel18.setText("Prenom :");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(249, 207, 21));
        jLabel19.setText("Sexe :");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(249, 207, 21));
        jLabel20.setText("Email :");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(249, 207, 21));
        jLabel21.setText("Mot de Passe :");

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(249, 207, 21));
        jLabel22.setText("Classe :");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(249, 207, 21));
        jLabel9.setText("Groupe :");

        profilNom.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        profilNom.setForeground(new java.awt.Color(255, 255, 255));

        profilPrenom.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        profilPrenom.setForeground(new java.awt.Color(255, 255, 255));

        profilSexe.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        profilSexe.setForeground(new java.awt.Color(255, 255, 255));

        profilMail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        profilMail.setForeground(new java.awt.Color(255, 255, 255));

        profilMdp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        profilMdp.setForeground(new java.awt.Color(255, 255, 255));

        profilClasse.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        profilClasse.setForeground(new java.awt.Color(255, 255, 255));

        profilGrp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        profilGrp.setForeground(new java.awt.Color(255, 255, 255));

        profilButChangeMdp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetbd1/images/Changer75px.png"))); // NOI18N
        profilButChangeMdp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profilButChangeMdpMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(249, 207, 21));
        jLabel2.setText("Date de naissance :");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("*******");

        profilDateN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        profilDateN.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout JPanel10Layout = new javax.swing.GroupLayout(JPanel10);
        JPanel10.setLayout(JPanel10Layout);
        JPanel10Layout.setHorizontalGroup(
            JPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(JPanel10Layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addGroup(JPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22)
                    .addComponent(jLabel9)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(profilMail)
                    .addGroup(JPanel10Layout.createSequentialGroup()
                        .addGroup(JPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JPanel10Layout.createSequentialGroup()
                                .addComponent(profilClasse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(profilMdp))
                            .addComponent(profilNom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(profilSexe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(profilPrenom, javax.swing.GroupLayout.DEFAULT_SIZE, 642, Short.MAX_VALUE)
                            .addComponent(profilDateN)
                            .addGroup(JPanel10Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(profilButChangeMdp))
                            .addComponent(profilGrp, javax.swing.GroupLayout.DEFAULT_SIZE, 642, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(JPanel10Layout.createSequentialGroup()
                .addGap(252, 252, 252)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 284, Short.MAX_VALUE))
        );
        JPanel10Layout.setVerticalGroup(
            JPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanel10Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel16)
                .addGap(40, 40, 40)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120)
                .addGroup(JPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(profilNom))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(profilPrenom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(profilSexe)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(profilMail)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(profilDateN))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel21)
                        .addComponent(jLabel3))
                    .addComponent(profilButChangeMdp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(JPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(profilMdp)
                    .addGroup(JPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel22)
                        .addComponent(profilClasse)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(profilGrp))
                .addGap(146, 146, 146))
        );

        javax.swing.GroupLayout profilPaneLayout = new javax.swing.GroupLayout(profilPane);
        profilPane.setLayout(profilPaneLayout);
        profilPaneLayout.setHorizontalGroup(
            profilPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        profilPaneLayout.setVerticalGroup(
            profilPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profilPaneLayout.createSequentialGroup()
                .addComponent(JPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        mainPane.addTab("Profil", profilPane);

        notesPane.setBackground(new java.awt.Color(39, 26, 54));

        jPanel9.setBackground(new java.awt.Color(39, 26, 54));
        jPanel9.setForeground(new java.awt.Color(39, 26, 54));

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetbd1/images/notes100px.png"))); // NOI18N

        jPanel8.setBackground(new java.awt.Color(249, 207, 21));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        notesTab.setBackground(new java.awt.Color(39, 26, 54));
        notesTab.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        notesTab.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        notesTab.setForeground(new java.awt.Color(249, 207, 21));
        notesTab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Date", "Nom", "Matiere", "Note"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        notesTab.setGridColor(new java.awt.Color(249, 207, 21));
        jScrollPane4.setViewportView(notesTab);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetbd1/images/moyenneDenv1.png"))); // NOI18N

        notesCBMatiere.setBackground(new java.awt.Color(39, 26, 54));
        notesCBMatiere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notesCBMatiereActionPerformed(evt);
            }
        });

        notesButMoyenneMatiere.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetbd1/images/calculer75.png"))); // NOI18N
        notesButMoyenneMatiere.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                notesButMoyenneMatiereMouseClicked(evt);
            }
        });

        notesMatiere.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        notesMatiere.setForeground(new java.awt.Color(255, 255, 255));
        notesMatiere.setText("                 ");
        notesMatiere.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(249, 207, 21)));

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetbd1/images/moyGen175.png"))); // NOI18N

        notesGeneral.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        notesGeneral.setForeground(new java.awt.Color(255, 255, 255));
        notesGeneral.setText("               ");
        notesGeneral.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(249, 207, 21)));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(7, 7, 7)
                                .addComponent(notesCBMatiere, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(notesButMoyenneMatiere, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(notesMatiere))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabel33)
                                .addGap(18, 18, 18)
                                .addComponent(notesGeneral))
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 802, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(405, 405, 405)
                        .addComponent(jLabel30)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel30)
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(notesCBMatiere)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(notesButMoyenneMatiere, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addComponent(notesMatiere)
                        .addGap(34, 34, 34)))
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(notesGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(122, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout notesPaneLayout = new javax.swing.GroupLayout(notesPane);
        notesPane.setLayout(notesPaneLayout);
        notesPaneLayout.setHorizontalGroup(
            notesPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        notesPaneLayout.setVerticalGroup(
            notesPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        mainPane.addTab("Notes", notesPane);

        planningPane.setBackground(new java.awt.Color(39, 26, 54));

        planningPANE.setBackground(new java.awt.Color(39, 26, 54));

        jLabel10.setForeground(new java.awt.Color(249, 207, 21));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetbd1/images/planningttle2.png"))); // NOI18N

        jPanel12.setBackground(new java.awt.Color(249, 207, 21));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetbd1/images/titre1.png"))); // NOI18N

        planningTab.setBackground(new java.awt.Color(39, 26, 54));
        planningTab.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(249, 207, 21)));
        planningTab.setForeground(new java.awt.Color(249, 207, 21));
        planningTab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Date", "8h - 10h", "10h - 12h", "14h - 16h", "16h - 18h"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        planningTab.setGridColor(new java.awt.Color(249, 207, 21));
        jScrollPane6.setViewportView(planningTab);

        jLabel39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetbd1/images/titre2.png"))); // NOI18N

        planningExamTab.setBackground(new java.awt.Color(39, 26, 54));
        planningExamTab.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(249, 207, 21)));
        planningExamTab.setForeground(new java.awt.Color(249, 207, 21));
        planningExamTab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Matière", "salle", "Heure"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        planningExamTab.setGridColor(new java.awt.Color(249, 207, 21));
        jScrollPane7.setViewportView(planningExamTab);

        jPanel17.setBackground(new java.awt.Color(249, 207, 21));

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        planningButRechercher.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetbd1/images/rechercher2.png"))); // NOI18N
        planningButRechercher.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                planningButRechercherMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout planningPANELayout = new javax.swing.GroupLayout(planningPANE);
        planningPANE.setLayout(planningPANELayout);
        planningPANELayout.setHorizontalGroup(
            planningPANELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(planningPANELayout.createSequentialGroup()
                .addGroup(planningPANELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(planningPANELayout.createSequentialGroup()
                        .addGap(516, 516, 516)
                        .addComponent(planningButRechercher))
                    .addGroup(planningPANELayout.createSequentialGroup()
                        .addGap(335, 335, 335)
                        .addComponent(jLabel38))
                    .addGroup(planningPANELayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 851, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(planningPANELayout.createSequentialGroup()
                .addGroup(planningPANELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(planningPANELayout.createSequentialGroup()
                        .addGap(347, 347, 347)
                        .addComponent(jLabel10))
                    .addGroup(planningPANELayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 870, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(planningPANELayout.createSequentialGroup()
                        .addGap(338, 338, 338)
                        .addGroup(planningPANELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(planningCBMatiere, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel39))))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        planningPANELayout.setVerticalGroup(
            planningPANELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(planningPANELayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(planningPANELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(planningCBMatiere, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(planningButRechercher, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout planningPaneLayout = new javax.swing.GroupLayout(planningPane);
        planningPane.setLayout(planningPaneLayout);
        planningPaneLayout.setHorizontalGroup(
            planningPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(planningPANE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        planningPaneLayout.setVerticalGroup(
            planningPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(planningPANE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        mainPane.addTab("Planning", planningPane);

        contactPane.setBackground(new java.awt.Color(39, 26, 54));

        contactPanel.setBackground(new java.awt.Color(39, 26, 54));

        jLabel11.setForeground(new java.awt.Color(249, 207, 21));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetbd1/images/contacter2.png"))); // NOI18N

        jPanel18.setBackground(new java.awt.Color(249, 207, 21));

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        jLabel41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetbd1/images/mesprofs2.png"))); // NOI18N

        contactTabEleve.setBackground(new java.awt.Color(39, 26, 54));
        contactTabEleve.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(249, 207, 21)));
        contactTabEleve.setForeground(new java.awt.Color(249, 207, 21));
        contactTabEleve.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nom", "Prénom", "Email"
            }
        ));
        contactTabEleve.setGridColor(new java.awt.Color(249, 207, 21));
        jScrollPane8.setViewportView(contactTabEleve);
        if (contactTabEleve.getColumnModel().getColumnCount() > 0) {
            contactTabEleve.getColumnModel().getColumn(2).setResizable(false);
            contactTabEleve.getColumnModel().getColumn(2).setPreferredWidth(200);
        }

        jLabel42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetbd1/images/mesCollegues2.png"))); // NOI18N

        jPanel19.setBackground(new java.awt.Color(249, 207, 21));

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        contactTabProf.setBackground(new java.awt.Color(39, 26, 54));
        contactTabProf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(249, 207, 21)));
        contactTabProf.setForeground(new java.awt.Color(249, 207, 21));
        contactTabProf.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nom", "Prénom", "Matiere", "Email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        contactTabProf.setGridColor(new java.awt.Color(249, 207, 21));
        jScrollPane9.setViewportView(contactTabProf);
        if (contactTabProf.getColumnModel().getColumnCount() > 0) {
            contactTabProf.getColumnModel().getColumn(3).setResizable(false);
            contactTabProf.getColumnModel().getColumn(3).setPreferredWidth(200);
        }

        contactJTF.setBackground(new java.awt.Color(39, 26, 54));
        contactJTF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        contactJTF.setForeground(new java.awt.Color(249, 207, 21));
        contactJTF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(249, 207, 21)));
        contactJTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                contactJTFKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                contactJTFKeyReleased(evt);
            }
        });

        recherche.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetbd1/images/searchIcon3.png"))); // NOI18N
        recherche.setText("jLabel43");
        recherche.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rechercheMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout contactPanelLayout = new javax.swing.GroupLayout(contactPanel);
        contactPanel.setLayout(contactPanelLayout);
        contactPanelLayout.setHorizontalGroup(
            contactPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contactPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(contactPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contactPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 812, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contactPanelLayout.createSequentialGroup()
                        .addComponent(jLabel42)
                        .addGap(399, 399, 399))))
            .addGroup(contactPanelLayout.createSequentialGroup()
                .addGroup(contactPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contactPanelLayout.createSequentialGroup()
                        .addGap(361, 361, 361)
                        .addComponent(recherche, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(contactJTF, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(contactPanelLayout.createSequentialGroup()
                        .addGap(415, 415, 415)
                        .addComponent(jLabel41))
                    .addGroup(contactPanelLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 832, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(contactPanelLayout.createSequentialGroup()
                        .addGap(372, 372, 372)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        contactPanelLayout.setVerticalGroup(
            contactPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contactPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jLabel41)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(contactPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contactJTF, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(recherche, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );

        javax.swing.GroupLayout contactPaneLayout = new javax.swing.GroupLayout(contactPane);
        contactPane.setLayout(contactPaneLayout);
        contactPaneLayout.setHorizontalGroup(
            contactPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contactPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(contactPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        contactPaneLayout.setVerticalGroup(
            contactPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contactPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        mainPane.addTab("Contact", contactPane);

        javax.swing.GroupLayout jPanel6_AccueilLayout = new javax.swing.GroupLayout(jPanel6_Accueil);
        jPanel6_Accueil.setLayout(jPanel6_AccueilLayout);
        jPanel6_AccueilLayout.setHorizontalGroup(
            jPanel6_AccueilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6_AccueilLayout.createSequentialGroup()
                .addComponent(mainPane, javax.swing.GroupLayout.PREFERRED_SIZE, 937, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel6_AccueilLayout.setVerticalGroup(
            jPanel6_AccueilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6_AccueilLayout.createSequentialGroup()
                .addComponent(mainPane, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6_Accueil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel6_Accueil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        jPanel5.setBackground(new java.awt.Color(249, 207, 21));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel44MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel44MouseClicked
        // logout
        int logout = JOptionPane.showConfirmDialog(this, "Etes-vous sûr de vouloir vous déconnecter ?", "Log out", 0);
        this.pack();
        if (logout==JOptionPane.YES_OPTION)
        {
            this.dispose();
            Login page = new Login();
            page.setVisible(true); }
    }//GEN-LAST:event_jLabel44MouseClicked

    private void contactMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contactMouseClicked
        contact.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetbd1/images/Clicked/contactClicked.png")));
        accueil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetbd1/images/accueil.png")));
        profil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetbd1/images/profil.png")));
        notes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetbd1/images/notes.png")));
        planning.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetbd1/images/planning.png")));
        mainPane.setSelectedComponent(contactPane);
        
        String requete = "select distinct nomProf as Nom, prenomProf as Prenom, nomMatiere as Matiere, mailProf as Mail from Avoir natural join Seance natural join Matiere natural join Professeur where idGroupe = (select idGroupe from Eleve where numEtu = "+ numEtu + ");" ;
        BaseDonneeUG.metDansJTable(requete, contactTabProf, 10 ,4);
        
        requete = "select distinct nomEtu as Nom, prenomEtu as Prenom,nomGroupe as Groupe, mailEtu as Mail from Eleve natural join Groupe where idClasse = (select idClasse from Eleve where numEtu = "+ numEtu + ") and numEtu != "+numEtu+";" ;
        BaseDonneeUG.metDansJTable(requete, contactTabEleve, 10 ,4);

    }//GEN-LAST:event_contactMouseClicked

    private void planningMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_planningMouseClicked
        planning.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetbd1/images/Clicked/planningClicked.png")));
        accueil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetbd1/images/accueil.png")));
        profil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetbd1/images/profil.png")));
        notes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetbd1/images/notes.png")));
        contact.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetbd1/images/contact.png")));
        mainPane.setSelectedComponent(planningPane);
        
        String dateDuJour = "2018-04-08"; //est normalement la date du jour actuel mais pour la correction on a mis une date arbitraire qui correspondra à des données
        String requete = "select dateControle as Date ,nomMatiere as Matiere ,idSalle as Salle,heureDebutCont as Debut,heureFinCont as Fin from Controle natural join Passer where idGroupe= (select idGroupe from Eleve where numEtu ="+numEtu+") and dateControle > '"+dateDuJour+"' order by DateControle";
        BaseDonneeUG.metDansJTable(requete,planningExamTab,9,5);
        BaseDonneeUG.metDansJTablePlanningEleve(planningTab,numEtu,20,5,dateDuJour);
        requete = "select distinct nomMatiere from Controle natural join Passer where idGroupe= (select idGroupe from Eleve where numEtu ="+numEtu+") and dateControle > '"+dateDuJour+"' order by DateControle";
        BaseDonneeUG.metDansComboBox(requete,planningCBMatiere);
    }//GEN-LAST:event_planningMouseClicked

    private void notesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_notesMouseClicked
        
        notes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetbd1/images/Clicked/notesClicked.png")));
        accueil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetbd1/images/accueil.png")));
        profil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetbd1/images/profil.png")));
        planning.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetbd1/images/planning.png")));
        contact.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetbd1/images/contact.png")));
        mainPane.setSelectedComponent(notesPane);
        String requete = "select DateControle as Date, intitule as Controle,nomMatiere as Matiere, note as Note from Controle natural join Note where numEtu ="+numEtu+" order by DateControle;";
        BaseDonneeUG.metDansJTable(requete, notesTab, 10, 4);
        requete = "select sum(MoyenneMatiere)/count(MoyenneMatiere) from (select nomMatiere,sum(note)/count(note) as MoyenneMatiere from Controle natural join Note where numEtu ="+numEtu+" group by nomMatiere);";
        BaseDonneeUG.metDansJLabel(requete,notesGeneral);
        requete = "select distinct NomMatiere from Controle natural join Note where numEtu ="+numEtu+";";
        BaseDonneeUG.metDansComboBox(requete,notesCBMatiere);
        
    }//GEN-LAST:event_notesMouseClicked

    private void profilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profilMouseClicked
        profil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetbd1/images/Clicked/profilClicked.png")));
        accueil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetbd1/images/accueil.png")));
        notes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetbd1/images/notes.png")));
        planning.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetbd1/images/planning.png")));
        contact.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetbd1/images/contact.png")));
        mainPane.setSelectedComponent(profilPane);
        BaseDonneeUG.metDansJLabel("select nomEtu from Eleve where numEtu = "+numEtu+";", profilNom);
        BaseDonneeUG.metDansJLabel("select prenomEtu from Eleve where numEtu = "+numEtu+";", profilPrenom);
        BaseDonneeUG.metDansJLabel("select sexeEtu from Eleve where numEtu = "+numEtu+";", profilSexe);
        BaseDonneeUG.metDansJLabel("select DateNaisEtu from Eleve where numEtu = "+numEtu+";", profilDateN);
        BaseDonneeUG.metDansJLabel("select mailEtu from Eleve where numEtu = "+numEtu+";", profilMail);
        BaseDonneeUG.metDansJLabel("select nomClasse from Eleve natural join Classe where numEtu = "+numEtu+";", profilClasse);
        BaseDonneeUG.metDansJLabel("select nomGroupe from Eleve natural join Groupe where numEtu = "+numEtu+";", profilGrp);
    }//GEN-LAST:event_profilMouseClicked

    private void accueilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accueilMouseClicked
        accueil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetbd1/images/Clicked/accueilClicked.png")));
        profil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetbd1/images/profil.png")));
        notes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetbd1/images/notes.png")));
        planning.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetbd1/images/planning.png")));
        contact.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetbd1/images/contact.png")));
        mainPane.setSelectedComponent(accueilPane);

            String dateDuJour = "2018-04-08"; //est normalement la date du jour actuel mais pour la correction on a mis une date arbitraire qui correspondra à des données
            String requete = "select dateControle as Date ,nomMatiere as Matiere ,idSalle as Salle,heureDebutCont as Debut,heureFinCont as Fin from Controle natural join Passer where idGroupe= (select idGroupe from Eleve where numEtu ="+numEtu+") and dateControle > '"+dateDuJour+"' order by DateControle";
            BaseDonneeUG.metDansJTablePlanningEleve(accueilCoursTab,numEtu,10,5,dateDuJour);
            BaseDonneeUG.metDansJTable(requete,accueilExamTab,3,5 );
    }//GEN-LAST:event_accueilMouseClicked

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
        // hoover / enter change logo color

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetbd1/images/logoM.png")));

    }//GEN-LAST:event_jLabel1MouseExited

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        // hoover / enter change logo color

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetbd1/images/Clicked/logoMClicked.png")));

    }//GEN-LAST:event_jLabel1MouseEntered

    private void notesButMoyenneMatiereMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_notesButMoyenneMatiereMouseClicked
        String matiere = notesCBMatiere.getSelectedItem().toString();
        String requete = "select sum(note)/count(note) as MoyenneMatiere from Controle natural join Note where numEtu ="+numEtu+" group by nomMatiere having nomMatiere = '"+matiere+"';";
        BaseDonneeUG.metDansJLabel(requete,notesMatiere);
    }//GEN-LAST:event_notesButMoyenneMatiereMouseClicked

    private void planningButRechercherMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_planningButRechercherMouseClicked
        String dateDuJour = "2018-04-08"; //est normalement la date du jour actuel mais pour la correction on a mis une date arbitraire qui correspondra à des données
        String matiere = planningCBMatiere.getSelectedItem().toString();
        String requete = "select dateControle as Date ,nomMatiere as Matiere ,idSalle as Salle,heureDebutCont as Debut,heureFinCont as Fin from Controle natural join Passer where idGroupe= (select idGroupe from Eleve where numEtu ="+numEtu+") and dateControle > '"+dateDuJour+"' and nomMatiere ='"+matiere+"' order by DateControle";
        BaseDonneeUG.metDansJTable(requete,planningExamTab,9,5);
    }//GEN-LAST:event_planningButRechercherMouseClicked

    private void rechercheMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rechercheMouseClicked
        rechercheEleve();
    }//GEN-LAST:event_rechercheMouseClicked

    private void contactJTFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contactJTFKeyPressed
        if (evt.getKeyChar()==java.awt.event.KeyEvent.VK_ENTER){
            rechercheEleve();  
        }
    }//GEN-LAST:event_contactJTFKeyPressed

    private void mainPaneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainPaneMouseClicked
        switch (mainPane.getSelectedIndex()) {
            case 0:
                accueilMouseClicked(evt);
                break;
            case 1:
                profilMouseClicked(evt);
                break;
            case 2:
                notesMouseClicked(evt);
                break;
            case 3:
                planningMouseClicked(evt);
                break;
            default:
                contactMouseClicked(evt);
                break;
        }
    }//GEN-LAST:event_mainPaneMouseClicked

    private void contactJTFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contactJTFKeyReleased
        String rec = contactJTF.getText();
        String requete;
        requete = "select nomEtu as Nom,prenomEtu as Prénom,nomClasse as Classe, mailEtu as Mail from Eleve natural join Classe where (nomEtu like '"+rec+"%' or prenomEtu like '"+rec+"%')";
        BaseDonneeUG.metDansJTable(requete, contactTabEleve,40,4);    }//GEN-LAST:event_contactJTFKeyReleased

    private void profilButChangeMdpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profilButChangeMdpMouseClicked
        this.dispose();
        ChangerMDP page = new ChangerMDP(numEtu,"Eleve");
        page.setVisible(true);
    }//GEN-LAST:event_profilButChangeMdpMouseClicked

    private void notesCBMatiereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notesCBMatiereActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_notesCBMatiereActionPerformed

    private void rechercheEleve(){
        String rec = contactJTF.getText();
        String[] nom = rec.split(" ");
        String requete;
        if (nom.length >= 2){
            requete = "select nomEtu as Nom,prenomEtu as Prénom,nomClasse as Classe, mailEtu as Mail from Eleve natural join Classe where (nomEtu ='"+nom[0]+"' and prenomEtu='"+nom[1]+"') or (nomEtu ='"+nom[1]+"' and prenomEtu='"+nom[0]+"') or (nomEtu ='"+nom[0]+"-"+nom[1]+"') or (prenomEtu ='"+nom[0]+"-"+nom[1]+"');";
            BaseDonneeUG.metDansJTable(requete, contactTabEleve,40,4);
        } else {
            nom = rec.split("_");
            if (nom.length >= 2){
                requete = "select nomEtu as Nom,prenomEtu as Prénom,nomClasse as Classe, mailEtu as Mail from Eleve natural join Classe where (nomEtu ='"+nom[0]+"' and prenomEtu='"+nom[1]+"') or (nomEtu ='"+nom[1]+"' and prenomEtu='"+nom[0]+"');";
                BaseDonneeUG.metDansJTable(requete, contactTabEleve,40,4);
            } else {
                requete = "select nomEtu as Nom,prenomEtu as Prénom,nomClasse as Classe, mailEtu as Mail from Eleve natural join Classe where (nomEtu ='"+rec+"' or prenomEtu='"+rec+"');";
                BaseDonneeUG.metDansJTable(requete, contactTabEleve,40,4);
            }
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EtudiantP1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new EtudiantP1(0).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanel10;
    private javax.swing.JLabel accueil;
    private javax.swing.JTable accueilCoursTab;
    private javax.swing.JTable accueilExamTab;
    private javax.swing.JPanel accueilPane;
    private javax.swing.JLabel contact;
    private javax.swing.JTextField contactJTF;
    private javax.swing.JPanel contactPane;
    private javax.swing.JPanel contactPanel;
    private javax.swing.JTable contactTabEleve;
    private javax.swing.JTable contactTabProf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel6_Accueil;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTable jTable5;
    private javax.swing.JTabbedPane mainPane;
    private javax.swing.JLabel notes;
    private javax.swing.JLabel notesButMoyenneMatiere;
    private javax.swing.JComboBox<String> notesCBMatiere;
    private javax.swing.JLabel notesGeneral;
    private javax.swing.JLabel notesMatiere;
    private javax.swing.JPanel notesPane;
    private javax.swing.JTable notesTab;
    private javax.swing.JLabel planning;
    private javax.swing.JLabel planningButRechercher;
    private javax.swing.JComboBox<String> planningCBMatiere;
    private javax.swing.JTable planningExamTab;
    private javax.swing.JPanel planningPANE;
    private javax.swing.JPanel planningPane;
    private javax.swing.JTable planningTab;
    private javax.swing.JLabel profil;
    private javax.swing.JLabel profilButChangeMdp;
    private javax.swing.JLabel profilClasse;
    private javax.swing.JLabel profilDateN;
    private javax.swing.JLabel profilGrp;
    private javax.swing.JLabel profilMail;
    private javax.swing.JLabel profilMdp;
    private javax.swing.JLabel profilNom;
    private javax.swing.JPanel profilPane;
    private javax.swing.JLabel profilPrenom;
    private javax.swing.JLabel profilSexe;
    private javax.swing.JLabel recherche;
    // End of variables declaration//GEN-END:variables
}
